class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'tr': {
      'app_title': 'Debtoff',
      'total_debt': 'Toplam Borç',
      'monthly_interest_payment': 'Aylık Faiz Ödemesi',
      'net_balance': 'Net Bakiye',
      'active_cards': 'Aktif Kartlarım',
      'card_limit_overdraft': 'Kart Limiti / Artı Para',
      'loan_debt': 'Kredi Borcu',
      'todo_list': 'Yapılacaklar Listesi',
      'this_month_payments': 'Bu Ayın Ödemeleri',
      'make_min_payment': 'Asgari ödemesini yap',
      'adjust_balance': 'Hesabı düzelt',
      'completed': 'Tamamlandı',
      'no_todo_items': 'Henüz yapılacak işlem yok.',
      'no_todo_sub': 'Seçtiğiniz ayda ödemeniz gereken asgari borç veya yüksek faizli hesap bulunmuyor.',
      
      'debts_empty_title': 'Borç Listeniz Boş',
      'debts_empty_sub': 'Takip edilecek kart veya artı para hesabı bulunamadı. İlk borcunuzu eklemek için sağ alttaki "+" butonuna tıklayın.',
      'add_new_debt': 'Yeni Borç Hesabı Ekle',
      'debt_type': 'Borç Türü',
      'bank_name_placeholder': 'Banka Adı (Örn: Akbank)',
      'total_debt_label': 'Toplam Borç',
      'monthly_interest_rate': 'Aylık Faiz Oranı (%)',
      'min_payment_optional': 'Asgari Ödeme (İsteğe Bağlı)',
      'min_payment_helper': 'Belirtmezseniz otomatik %20 hesaplanır.',
      'add_action': 'Ekle',
      'initial': 'Başlangıç',
      'min_payment': 'Min. Ödeme',
      'remaining': 'Kalan',
      'paid_pct': 'ödendi',
      'make_payment': 'Ödeme Yap',
      'balance_sync': 'Bakiye Eşitle',
      'payment_amount': 'Ödeme Tutarı',
      'payment_note_optional': 'Ödeme Nedeni (İsteğe Bağlı)',
      'save_payment': 'Ödemeyi Kaydet',
      'sync_balance_title': 'Bakiyeyi Eşitle',
      'sync_balance_sub': 'Ekstrenizdeki güncel faiz veya harcama tutarına göre borç bakiyesini doğrudan senkronize edin.',
      'current_statement_debt': 'Güncel Ekstre Borcu',
      'adjust_note_placeholder': 'Düzeltme Nedeni (Örn: Faiz yansıdı)',
      'save_adjustment': 'Bakiyeyi Eşitle ve Günlüğe Yaz',

      'ai_splitter': 'AI Ödeme Dağıtıcı',
      'ai_splitter_sub': 'Bütçenizi girin. Akıllı algoritmamız, yasal kart asgarilerinizi otomatik ayırdıktan sonra kalan parayı faiz yükünüzü en hızlı düşürecek şekilde dağıtır.',
      'monthly_payment_budget': 'Bu Ayki Ödeme Bütçeniz',
      'calculation_method': 'Hesaplama Yöntemi',
      'avalanche_method': 'Çığ Yöntemi (Avalanche)',
      'snowball_method': 'Kartopu Yöntemi (Snowball)',
      'calculate_plan': 'Ödeme Planını Hesapla',
      'insufficient_budget': 'Bütçe Yetersiz Uyarısı',
      'insufficient_budget_sub': 'Girdiğiniz bütçe kartlarınızın yasal asgari ödemeleri toplamını karşılamıyor. Bankalardan kart yapılandırması talep etmeniz önerilir.',
      'ai_preview_title': '📋 AI Dağıtım Planı Önizlemesi',
      'debt_closed': 'Borç Kapanmış',
      'debt_fully_closing': 'Borç Tamamen Kapanıyor!',
      'min_paid': 'Asgari Ödendi',
      'min_missing': 'Asgari Eksik',
      'apply_payments': 'Ödemeleri Uygula ve Günlüğe İşle',

      'no_journal': 'Henüz hareket kaydı yok.',
      'journal_sub': 'Yaptığınız ödemeler burada listelenir.',
      'delete_log_title': 'Kaydı Sil?',
      'delete_log_sub': 'Bu ödeme günlüğü kaydını silmek, borç bakiyenize eklenen tutarı geri ekleyecektir. Emin misiniz?',
      'cancel': 'Vazgeç',
      'delete_action': 'Evet, Sil',
      'delete_log': 'Kaydı Sil',

      'continue': 'Devam Et',
      'onboarding_finish_btn': 'Profilini Oluştur ve Başla',
      'welcome_title': 'Hoş Geldiniz',
      'feat1_title': 'Akıllı Borç Yönetimi',
      'feat1_sub': 'Tüm kart borçlarınızı, artı para hesaplarınızı ve faiz oranlarınızı tek bir yerden görün.',
      'feat2_title': 'AI Yapay Zeka Desteği',
      'feat2_sub': 'Bütçenizi en optimum şekilde dağıtan Çığ ve Kartopu algoritmalarıyla faiz yükünden kurtulun.',
      'feat3_title': 'Güvenli ve Gizli',
      'feat3_sub': 'Verileriniz sunucuya aktarılmaz, cihazınızda şifreli olarak 100% offline saklanır.',
      'enter_name_error': 'Lütfen adınızı girin',
      'profile_name': 'Profil Adı',
      'currency': 'Para Birimi',
      'passcode_title': 'Uygulama Kilidi Şifresi (PIN - 4 Hane)',
      'passcode_sub': 'Güvenli Giriş İçin Şifre Belirleyin',
      'passcode_active': 'Şifre Etkin',
      'skip_passcode': 'Şifresiz Devam Et',
      'passcode_entry': 'Şifre Girişi',
      'wrong_passcode': 'Şifre Yanlış',
      'recovery_key_title': 'Kurtarma Anahtarı',
      'recovery_key_sub': 'Şifrenizi unutursanız bu anahtarı kullanarak sıfırlayabilirsiniz. Lütfen bir yere not edin:',
      'reset_with_recovery': 'Kurtarma Anahtarı ile Sıfırla',
      'enter_recovery_key': 'Kurtarma Anahtarını Girin',
      'recovery_key_success': 'Kurtarma Anahtarı Doğru! Yeni PIN Belirleyebilirsiniz',
      'recovery_key_error': 'Kurtarma Anahtarı Geçersiz',
      'language': 'Dil',
      'settings': 'Ayarlar',
      'load_demo': 'Örnek Verileri Yükle',
      'reset_all': 'Tüm Verileri Sıfırla',
      'export_json': 'JSON Yedek Al',
      'import_json': 'Yedek Geri Yükle',
      'reset_app_warning': 'Uygulamayı Sıfırla',
      'reset_app_sub': 'Tüm borçlar ve profil silinecek. Bu işlem geri alınamaz. Emin misiniz?',
      'upgrade_premium': 'Premium\'a Yükselt',
      'premium_active': 'Premium Aktif',
      'premium_title': 'Debtoff Premium\'a Geçin',
      'premium_desc': 'Borçlarınızı daha akıllıca yönetin ve sınırlamaları kaldırın.',
      'premium_features': 'Premium Özellikler:',
      'feat_unlimited_debts': 'Sınırsız Borç Hesabı Takibi (Ücretsiz limit: 2)',
      'feat_advanced_ai': 'Gelişmiş AI Bütçe Dağıtım Stratejileri',
      'feat_premium_badge': 'Gold Tasarım Arayüzü ve Profil Rozeti',
      'feat_offline_backup': 'Sınırsız JSON Yedekleme ve Profil Kilidi',
      'buy_premium_btn': 'Premium\'a Yükselt (~100 TL / \$2.99)',
      'simulate_calculating': 'AI Borç Algoritması Çalıştırılıyor...',
      'simulate_avalanche': 'Çığ yöntemiyle faiz yükleri inceleniyor...',
      'simulate_snowball': 'Kartopu yöntemiyle bakiye büyüklükleri sıralanıyor...',
      'simulate_allocating': 'Yasal asgariler ayrılıyor ve bütçe dağıtılıyor...',
      'simulate_done': 'Optimal ödeme planı başarıyla hazırlandı!',
      'limit_reached_title': 'Borç Sınırına Ulaşıldı',
      'limit_reached_sub': 'Ücretsiz sürümde en fazla 2 adet borç hesabı takip edebilirsiniz. Sınırsız borç takibi için Premium\'a geçin.',
      'recovery_copied': 'Kurtarma anahtarı panoya kopyalandı!',

      // Missing Dashboard / Journal Keys
      'latest_stat': 'En son durum',
      'total_paid': 'Toplam Ödenen',
      'system_record': 'Sistem kaydı',
      'debt_free_ratio': 'Borç Azalma Oranı',
      'freedom_pct': 'Kurtulma yüzdesi',
      'active_cards_count': 'Aktif Borç Sayısı',
      'remaining_debts_desc': 'Kalan banka borcu',
      'towards_debt_free': 'Borçsuz Yaşama Doğru',
      'no_debts_yet': 'Henüz eklenmiş bir borcunuz bulunmuyor. Eklemek için borçlarım sekmesine gidebilirsiniz.',
      'cleared_so_far_msg': 'Başlangıçtan bu yana {paid} {curr} borç temizlediniz. Harika gidiyorsunuz!',
      'monthly_tasks': '⚡ Aylık Ödeme Görevleri',
      'no_debts_title': 'Hiç Borcunuz Yok!',
      'no_debts_sub': 'Takip edecek borç bulunamadı. Kendi borçlarınızı eklemek için "Borçlarım" sekmesine gidebilir veya Ayarlar\'dan örnek verileri yükleyebilirsiniz.',
      'no_tasks_month': 'Bu ay için tanımlı görev yok.',
      'no_journal_logs': 'Henüz hareket kaydı yok.',
      'delete_record': 'Kaydı Sil',
      'delete_record_title': 'Kaydı Sil?',
      'delete_record_sub': 'Bu ödeme günlüğü kaydını silmek, borç bakiyenize eklenen tutarı geri ekleyecektir. Emin misiniz?',
      'yes_delete': 'Evet, Sil',
      'ai_splitter_desc': 'Bütçenizi girin. Akıllı algoritmamız, yasal kart asgarilerinizi otomatik ayırdıktan sonra kalan parayı faiz yükünüzü en hızlı düşürecek şekilde dağıtır.',
      'monthly_budget_label': 'Bu Ayki Ödeme Bütçeniz',
      'avalanche_title': 'Çığ Yöntemi',
      'avalanche_sub': '(Önerilen - Yüksek Faiz)',
      'snowball_title': 'Kartopu Yöntemi',
      'snowball_sub': '(Küçük Borç Öncelikli)',
      'calculate_btn': 'Ödeme Planını Hesapla',
      'apply_payments_btn': 'Ödemeleri Uygula ve Günlüğe İşle',
      'payments_applied_msg': 'AI planına göre tüm borç ödemeleriniz başarıyla kaydedildi. İlerleme grafiğiniz güncellendi, borçlarınız biraz daha eridi! 🎉',
      'congratulations': 'Tebrikler!',
      'enter_budget_error': 'Lütfen geçerli bir bütçe girin.',
      'task_list': 'Görev Listesi',
      'checklist_payment': 'checklist ödemesi',
      'card_min_payment_task': '{bank} Kredi Kartı Asgari Ödemesi',
      'overdraft_clear_task': '{bank} Ek Para Kapatma Hedefi',
      'free_tasks_done': 'Tebrikler! Bu ay için tüm borçlarınızı tamamen temizlediniz. 🎉',
      'all_filter': 'Tümü',
      'select_month': 'Ay Seç',
      'date_range': 'Tarih Aralığı',
      'start_date': 'Başlangıç',
      'end_date': 'Bitiş',
      'clear_filter': 'Filtreyi Temizle',
      'filter_title': 'İşlem Filtreleme',

      // Backup import dialog
      'import_title': 'Yedek Veri Yapıştır',
      'import_desc': 'Daha önce kopyaladığınız JSON yedek metnini buraya yapıştırın:',
      'import_cancel': 'Vazgeç',
      'import_load': 'Yükle',
      'import_success': 'Yedek başarıyla geri yüklendi! 🔄',
      'import_error': 'Hatalı yedek verisi!',

      // Confirm warning dialog
      'confirm_title': 'Emin misiniz?',
      'confirm_cancel': 'Vazgeç',
      'confirm_yes': 'Evet',

      // IAP error messages
      'iap_unavailable': 'Uygulama içi satın alma şu anda kullanılamıyor. Lütfen daha sonra tekrar deneyin.',
      'iap_product_not_found': 'Ürün bilgisi alınamadı. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.',
      'iap_error': 'Satın alma sırasında bir hata oluştu. Lütfen tekrar deneyin.',
    },
    'en': {
      'app_title': 'Debtoff',
      'total_debt': 'Total Debt',
      'monthly_interest_payment': 'Monthly Interest Payment',
      'net_balance': 'Net Balance',
      'active_cards': 'My Active Cards',
      'card_limit_overdraft': 'Overdraft Limit / Balance',
      'loan_debt': 'Loan Debt',
      'todo_list': 'Checklist / Tasks',
      'this_month_payments': 'This Month\'s Payments',
      'make_min_payment': 'Pay minimum amount',
      'adjust_balance': 'Equalize balance',
      'completed': 'Completed',
      'no_todo_items': 'No tasks scheduled.',
      'no_todo_sub': 'There are no minimum card payments or high-interest overdraft items due this month.',
      
      'debts_empty_title': 'No Debts Registered',
      'debts_empty_sub': 'No active card, overdraft or loan accounts found. Click the "+" button below to add your first debt.',
      'add_new_debt': 'Add New Debt Account',
      'debt_type': 'Debt Type',
      'bank_name_placeholder': 'Bank Name (e.g. Chase)',
      'total_debt_label': 'Total Debt',
      'monthly_interest_rate': 'Monthly Interest Rate (%)',
      'min_payment_optional': 'Minimum Payment (Optional)',
      'min_payment_helper': 'If left blank, 20% will be automatically calculated.',
      'add_action': 'Add',
      'initial': 'Initial',
      'min_payment': 'Min. Payment',
      'remaining': 'Remaining',
      'paid_pct': 'paid',
      'make_payment': 'Make Payment',
      'balance_sync': 'Balance Sync',
      'payment_amount': 'Payment Amount',
      'payment_note_optional': 'Payment Note (Optional)',
      'save_payment': 'Save Payment',
      'sync_balance_title': 'Sync Balance',
      'sync_balance_sub': 'Directly sync the debt balance to reflect your statements, new expenses or interest charges.',
      'current_statement_debt': 'Current Statement Balance',
      'adjust_note_placeholder': 'Adjustment Reason (e.g. Interest applied)',
      'save_adjustment': 'Sync Balance & Log to Journal',

      'ai_splitter': 'AI Budget Splitter',
      'ai_splitter_sub': 'Enter your monthly payment budget. Our AI algorithm pays off card minimums first, then allocates the remainder to target high-interest items, minimizing your lifetime interest.',
      'monthly_payment_budget': 'Monthly Payment Budget',
      'calculation_method': 'Calculation Method',
      'avalanche_method': 'Avalanche Method (High Interest First)',
      'snowball_method': 'Snowball Method (Smallest Balance First)',
      'calculate_plan': 'Calculate Optimal Payments',
      'insufficient_budget': 'Insufficient Budget Alert',
      'insufficient_budget_sub': 'Your monthly budget is lower than the required minimum card payments. We advise contacting your banks for structuring.',
      'ai_preview_title': '📋 AI Allocation Preview',
      'text_closed': 'Closed',
      'debt_closed': 'Closed',
      'debt_fully_closing': 'Fully Paying Off!',
      'min_paid': 'Minimum Paid',
      'min_missing': 'Minimum Deficit',
      'apply_payments': 'Apply Payments & Log to Journal',

      'no_journal': 'No transaction logs yet.',
      'journal_sub': 'Your payments and adjustments history will appear here.',
      'delete_log_title': 'Delete Entry?',
      'delete_log_sub': 'Deleting this payment log will restore the amount back to your debt balance. Are you sure?',
      'cancel': 'Cancel',
      'delete_action': 'Yes, Delete',
      'delete_log': 'Delete Entry',

      'continue': 'Continue',
      'onboarding_finish_btn': 'Create Profile & Get Started',
      'welcome_title': 'Welcome',
      'feat1_title': 'Smart Debt Tracker',
      'feat1_sub': 'View all your cards, overdraft lines, and loans together in a single dashboard.',
      'feat2_title': 'AI-Powered Splitting',
      'feat2_sub': 'Eliminate high interest faster using optimized mathematical Avalanche or Snowball methods.',
      'feat3_title': '100% Private & Offline',
      'feat3_sub': 'Your financial records stay local. No servers, no signups, fully secure.',
      'enter_name_error': 'Please enter your name',
      'profile_name': 'Profile Name',
      'currency': 'Currency',
      'passcode_title': 'App Passcode Lock (4-Digit PIN)',
      'passcode_sub': 'Secure Your Records with a PIN',
      'passcode_active': 'Passcode Enabled',
      'skip_passcode': 'Continue without Passcode',
      'passcode_entry': 'Enter Passcode',
      'wrong_passcode': 'Incorrect PIN',
      'recovery_key_title': 'Recovery Key',
      'recovery_key_sub': 'Write down this offline key. If you forget your PIN, you can reset it using this key:',
      'reset_with_recovery': 'Reset with Recovery Key',
      'enter_recovery_key': 'Enter Recovery Key',
      'recovery_key_success': 'Recovery Key Verified! You can set a new PIN now',
      'recovery_key_error': 'Invalid Recovery Key',
      'language': 'Language',
      'settings': 'Settings',
      'load_demo': 'Load Demo Data',
      'reset_all': 'Factory Reset All Data',
      'export_json': 'Export Backup JSON',
      'import_json': 'Restore Backup JSON',
      'reset_app_warning': 'Reset App',
      'reset_app_sub': 'All profiles, PINs, and debts will be deleted. This cannot be undone. Are you sure?',
      'upgrade_premium': 'Upgrade to Premium',
      'premium_active': 'Premium Active',
      'premium_title': 'Upgrade to Debtoff Premium',
      'premium_desc': 'Manage your debts smarter and remove all limitations.',
      'premium_features': 'Premium Features:',
      'feat_unlimited_debts': 'Track Unlimited Debt Accounts (Free limit: 2)',
      'feat_advanced_ai': 'Advanced AI Budget Allocation Strategies',
      'feat_premium_badge': 'Gold Badge Profile Theme & Icons',
      'feat_offline_backup': 'Unlimited JSON backups & export/import options',
      'buy_premium_btn': 'Upgrade to Premium (~\$2.99 / 100 TL)',
      'simulate_calculating': 'Running AI Debt Algorithms...',
      'simulate_avalanche': 'Analysing interest rate weights (Avalanche method)...',
      'simulate_snowball': 'Sorting balance weights (Snowball method)...',
      'simulate_allocating': 'Satisfying card minimums and distributing remainder...',
      'simulate_done': 'Optimal payment plan calculated successfully!',
      'limit_reached_title': 'Debt Limit Reached',
      'limit_reached_sub': 'Free accounts can track up to 2 active debts. Upgrade to Premium for unlimited tracking.',
      'recovery_copied': 'Recovery key copied to clipboard!',

      // Missing Dashboard / Journal Keys
      'latest_stat': 'Latest status',
      'total_paid': 'Total Paid',
      'system_record': 'System record',
      'debt_free_ratio': 'Debt Reduction Rate',
      'freedom_pct': 'Freedom percentage',
      'active_cards_count': 'Active Debts Count',
      'remaining_debts_desc': 'Remaining bank debts',
      'towards_debt_free': 'Towards Debt-Free Life',
      'no_debts_yet': 'You don\'t have any debts registered. Go to the Debts tab to add your first one.',
      'cleared_so_far_msg': 'You have cleared {paid} {curr} debt since the beginning. Great job!',
      'monthly_tasks': '⚡ Monthly Payment Tasks',
      'no_debts_title': 'No Debts Remaining!',
      'no_debts_sub': 'No active debts to track. Go to the "Debts" tab to add your own, or load demo data from Settings.',
      'no_tasks_month': 'No tasks defined for this month.',
      'no_journal_logs': 'No transaction logs yet.',
      'delete_record': 'Delete Log',
      'delete_record_title': 'Delete Log?',
      'delete_record_sub': 'Deleting this payment log will restore the amount back to your debt balance. Are you sure?',
      'yes_delete': 'Yes, Delete',
      'ai_splitter_desc': 'Enter your budget. Our smart algorithm automatically reserves legal card minimums, then distributes the remainder to reduce interest payload fast.',
      'monthly_budget_label': 'Monthly Payment Budget',
      'avalanche_title': 'Avalanche Method',
      'avalanche_sub': '(Recommended - High Interest)',
      'snowball_title': 'Snowball Method',
      'snowball_sub': '(Smallest Balance First)',
      'calculate_btn': 'Calculate Payment Plan',
      'apply_payments_btn': 'Apply Payments & Write to Journal',
      'payments_applied_msg': 'All payments have been successfully applied according to the AI plan. Your progress chart is updated! 🎉',
      'congratulations': 'Congratulations!',
      'enter_budget_error': 'Please enter a valid budget.',
      'task_list': 'Task List',
      'checklist_payment': 'checklist payment',
      'card_min_payment_task': '{bank} Credit Card Minimum Payment',
      'overdraft_clear_task': '{bank} Overdraft Clear Goal',
      'free_tasks_done': 'Congratulations! You have fully cleared all your debts for this month. 🎉',
      
      // Journal filters
      'all_filter': 'All',
      'select_month': 'Select Month',
      'date_range': 'Date Range',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'clear_filter': 'Clear Filter',
      'filter_title': 'Filter Journal',

      // Backup import dialog
      'import_title': 'Paste Backup Data',
      'import_desc': 'Paste the JSON backup text you copied earlier:',
      'import_cancel': 'Cancel',
      'import_load': 'Load',
      'import_success': 'Backup restored successfully! 🔄',
      'import_error': 'Invalid backup data!',

      // Confirm warning dialog
      'confirm_title': 'Are you sure?',
      'confirm_cancel': 'Cancel',
      'confirm_yes': 'Yes',

      // IAP error messages
      'iap_unavailable': 'In-app purchases are currently unavailable. Please try again later.',
      'iap_product_not_found': 'Could not load product info. Please check your connection and try again.',
      'iap_error': 'An error occurred during purchase. Please try again.',
    }
  };

  static String translate(String langCode, String key) {
    return _translations[langCode]?[key] ?? _translations['tr']?[key] ?? key;
  }
}
